"""Prompt-pack content must be part of every LLM stage's cache key.

Model IDs were already keyed; prompt content was not, so once cross-run reuse
works an edited prompt would silently serve plans generated by the previous one.
Each stage's key is computed against a copy of the real prompt packs, so editing
one pack proves both that the affected stage's key changes and that unrelated
stages' keys do not.
"""

from __future__ import annotations

import json
from pathlib import Path
import shutil
from typing import Any
from unittest.mock import MagicMock

import pytest

from twinklr.core.agents._paths import AGENTS_BASE_PATH
from twinklr.core.agents.audio.lyrics.orchestrator import LyricsOrchestrator
from twinklr.core.agents.audio.profile.models import AudioProfileModel
from twinklr.core.agents.audio.profile.orchestrator import AudioProfileOrchestrator
from twinklr.core.agents.prompts import (
    MISSING_PACK_MARKER,
    prompt_pack_hash,
    prompt_packs_hash,
    spec_prompt_hash,
)
from twinklr.core.agents.sequencer.group_planner import orchestrator as group_module
from twinklr.core.agents.sequencer.group_planner.context import SectionPlanningContext
from twinklr.core.agents.sequencer.group_planner.orchestrator import GroupPlannerOrchestrator
from twinklr.core.agents.sequencer.group_planner.timing import (
    BarInfo,
    SectionBounds,
    TimingContext,
)
from twinklr.core.agents.sequencer.macro_planner import orchestrator as macro_module
from twinklr.core.agents.sequencer.macro_planner.context import PlanningContext
from twinklr.core.agents.sequencer.macro_planner.orchestrator import MacroPlannerOrchestrator
from twinklr.core.agents.sequencer.moving_heads.context import (
    FixtureContext,
    MovingHeadPlanningContext,
)
from twinklr.core.agents.sequencer.moving_heads.orchestrator import (
    MovingHeadPlannerOrchestrator,
)
from twinklr.core.agents.spec import AgentSpec
from twinklr.core.audio.models import SongBundle
from twinklr.core.sequencer.templates.group.catalog import TemplateCatalog, TemplateInfo
from twinklr.core.sequencer.templates.group.models.choreography import (
    ChoreographyGraph,
    ChoreoGroup,
)
from twinklr.core.sequencer.timing import TimeRef
from twinklr.core.sequencer.vocabulary import GroupTemplateType, GroupVisualIntent
from twinklr.core.sequencer.vocabulary.timing import TimeRefKind

FIXTURES = Path(__file__).parent.parent.parent / "fixtures" / "audio_profile"

# Prompt packs each stage renders, keyed by the base path they resolve against.
MACRO_PACKS = ("sequencer/macro_planner/prompts",)
GROUP_PACKS = ("sequencer/group_planner/prompts",)
MOVING_HEADS_PACKS = ("sequencer/moving_heads/prompts",)


@pytest.fixture
def agents_base(tmp_path: Path) -> Path:
    """Copy of the real planner prompt packs, safe to edit.

    Laid out as ``<tmp>/agents/...`` because the moving-heads specs name their
    packs relative to the ``core`` directory, one level above ``agents``.
    """
    base = tmp_path / "agents"
    for relative in MACRO_PACKS + GROUP_PACKS + MOVING_HEADS_PACKS:
        shutil.copytree(AGENTS_BASE_PATH / relative, base / relative)
    return base


@pytest.fixture
def audio_packs(tmp_path: Path) -> Path:
    """Copy of the audio-agent prompt packs (base path holds both packs)."""
    packs = tmp_path / "audio_packs"
    packs.mkdir()
    shutil.copytree(
        AGENTS_BASE_PATH / "audio/profile/prompts/audio_profile", packs / "audio_profile"
    )
    shutil.copytree(AGENTS_BASE_PATH / "audio/lyrics/prompts/lyrics", packs / "lyrics")
    return packs


@pytest.fixture
def song_bundle() -> SongBundle:
    return SongBundle(**json.loads((FIXTURES / "need_a_favor_song_bundle.json").read_text()))


@pytest.fixture
def audio_profile() -> AudioProfileModel:
    return AudioProfileModel(**json.loads((FIXTURES / "audio_profile_model.json").read_text()))


@pytest.fixture
def provider() -> MagicMock:
    return MagicMock()


@pytest.fixture
def macro_context(audio_profile: AudioProfileModel) -> PlanningContext:
    return PlanningContext(
        audio_profile=audio_profile,
        lyric_context=None,
        display_groups=[{"id": "OUTLINE", "role_key": "OUTLINE", "model_count": 10}],
    )


@pytest.fixture
def moving_heads_context(audio_profile: AudioProfileModel) -> MovingHeadPlanningContext:
    return MovingHeadPlanningContext(
        audio_profile=audio_profile,
        fixtures=FixtureContext(count=4, groups=[{"id": "ALL", "fixtures": [1, 2, 3, 4]}]),
        available_templates=["mh_sweep"],
    )


@pytest.fixture
def section_context() -> SectionPlanningContext:
    return SectionPlanningContext(
        section_id="verse_1",
        section_name="verse",
        start_ms=0,
        end_ms=2000,
        energy_target="MED",
        motion_density="MED",
        choreography_style="HYBRID",
        primary_focus_targets=["HERO"],
        secondary_targets=["ARCHES"],
        notes=None,
        choreo_graph=ChoreographyGraph(
            graph_id="test",
            groups=[ChoreoGroup(id="HERO_1", role="HERO")],
        ),
        template_catalog=TemplateCatalog(
            entries=[
                TemplateInfo(
                    template_id="gtpl_accent_flash",
                    version="1.0",
                    name="Flash",
                    template_type=GroupTemplateType.ACCENT,
                    visual_intent=GroupVisualIntent.TEXTURE,
                    tags=(),
                )
            ]
        ),
        timing_context=TimingContext(
            song_duration_ms=8000,
            beats_per_bar=4,
            bar_map={1: BarInfo(bar=1, start_ms=0, duration_ms=2000)},
            section_bounds={
                "verse_1": SectionBounds(
                    section_id="verse_1",
                    start=TimeRef(kind=TimeRefKind.BAR_BEAT, bar=1, beat=1),
                    end=TimeRef(kind=TimeRefKind.BAR_BEAT, bar=2, beat=1),
                )
            },
        ),
    )


def _edit_prompt(pack_dir: Path) -> None:
    """Simulate a prompt fix landing in one pack."""
    system = pack_dir / "system.j2"
    system.write_text(system.read_text() + "\nAlways honor recommended_sections.\n")


async def _stage_keys(
    *,
    provider: MagicMock,
    agents_base: Path,
    audio_packs: Path,
    monkeypatch: pytest.MonkeyPatch,
    macro_context: PlanningContext,
    section_context: SectionPlanningContext,
    moving_heads_context: MovingHeadPlanningContext,
    song_bundle: SongBundle,
) -> dict[str, str]:
    """Compute every LLM stage's cache key against the temporary packs."""
    monkeypatch.setattr(macro_module, "AGENTS_BASE_PATH", agents_base)
    monkeypatch.setattr(group_module, "AGENTS_BASE_PATH", agents_base)

    return {
        "profile": await AudioProfileOrchestrator(
            provider=provider, prompt_base_path=audio_packs
        ).get_cache_key(song_bundle),
        "lyrics": await LyricsOrchestrator(
            provider=provider, prompt_base_path=audio_packs
        ).get_cache_key(song_bundle),
        "macro": await MacroPlannerOrchestrator(provider=provider).get_cache_key(macro_context),
        "group": await GroupPlannerOrchestrator(provider=provider).get_cache_key(section_context),
        "moving_heads": await MovingHeadPlannerOrchestrator(
            provider=provider, prompt_base_path=agents_base.parent
        ).get_cache_key(moving_heads_context),
    }


@pytest.fixture
async def stage_keys(
    provider: MagicMock,
    agents_base: Path,
    audio_packs: Path,
    monkeypatch: pytest.MonkeyPatch,
    macro_context: PlanningContext,
    section_context: SectionPlanningContext,
    moving_heads_context: MovingHeadPlanningContext,
    song_bundle: SongBundle,
) -> dict[str, Any]:
    """Baseline keys plus a callable that recomputes them after an edit."""

    async def compute() -> dict[str, str]:
        return await _stage_keys(
            provider=provider,
            agents_base=agents_base,
            audio_packs=audio_packs,
            monkeypatch=monkeypatch,
            macro_context=macro_context,
            section_context=section_context,
            moving_heads_context=moving_heads_context,
            song_bundle=song_bundle,
        )

    return {"baseline": await compute(), "recompute": compute}


class TestPromptEditInvalidation:
    """The fingerprint addendum: a prompt edit must invalidate its own stages."""

    async def test_prompt_edit_invalidates_stage_key(
        self, stage_keys: dict[str, Any], agents_base: Path
    ) -> None:
        _edit_prompt(agents_base / "sequencer/macro_planner/prompts/planner")

        after = await stage_keys["recompute"]()

        assert after["macro"] != stage_keys["baseline"]["macro"]

    async def test_unrelated_stage_key_unchanged_by_prompt_edit(
        self, stage_keys: dict[str, Any], agents_base: Path
    ) -> None:
        _edit_prompt(agents_base / "sequencer/macro_planner/prompts/planner")

        after = await stage_keys["recompute"]()
        baseline = stage_keys["baseline"]

        for stage in ("profile", "lyrics", "group", "moving_heads"):
            assert after[stage] == baseline[stage], f"{stage} key changed for someone else's prompt"

    async def test_judge_prompt_edit_invalidates_its_stage(
        self, stage_keys: dict[str, Any], agents_base: Path
    ) -> None:
        """Both packs a stage renders are keyed, not just the planner's."""
        _edit_prompt(agents_base / "sequencer/macro_planner/prompts/judge")

        after = await stage_keys["recompute"]()

        assert after["macro"] != stage_keys["baseline"]["macro"]

    async def test_audio_prompt_edit_is_scoped_to_its_agent(
        self, stage_keys: dict[str, Any], audio_packs: Path
    ) -> None:
        _edit_prompt(audio_packs / "audio_profile")

        after = await stage_keys["recompute"]()
        baseline = stage_keys["baseline"]

        assert after["profile"] != baseline["profile"]
        assert after["lyrics"] == baseline["lyrics"]

    async def test_keys_are_stable_without_edits(self, stage_keys: dict[str, Any]) -> None:
        assert await stage_keys["recompute"]() == stage_keys["baseline"]


class TestModelIdRemainsKeyed:
    """Do not regress the one property the addendum already found sound."""

    async def test_model_id_still_in_every_llm_stage_key(
        self,
        provider: MagicMock,
        audio_packs: Path,
        macro_context: PlanningContext,
        section_context: SectionPlanningContext,
        moving_heads_context: MovingHeadPlanningContext,
        song_bundle: SongBundle,
    ) -> None:
        profile = AudioProfileOrchestrator(provider=provider, prompt_base_path=audio_packs)
        retargeted_profile = AudioProfileOrchestrator(
            provider=provider, model="gpt-5.6", prompt_base_path=audio_packs
        )
        assert await profile.get_cache_key(song_bundle) != await retargeted_profile.get_cache_key(
            song_bundle
        )

        lyrics = LyricsOrchestrator(provider=provider, prompt_base_path=audio_packs)
        retargeted_lyrics = LyricsOrchestrator(
            provider=provider, model="gpt-5.6", prompt_base_path=audio_packs
        )
        assert await lyrics.get_cache_key(song_bundle) != await retargeted_lyrics.get_cache_key(
            song_bundle
        )

        macro = MacroPlannerOrchestrator(provider=provider)
        retargeted_macro = MacroPlannerOrchestrator(
            provider=provider,
            planner_spec=_retarget(macro.planner_spec),
            judge_spec=macro.judge_spec,
        )
        assert await macro.get_cache_key(macro_context) != await retargeted_macro.get_cache_key(
            macro_context
        )

        group = GroupPlannerOrchestrator(provider=provider)
        retargeted_group = GroupPlannerOrchestrator(
            provider=provider,
            planner_spec=_retarget(group.planner_spec),
            section_judge_spec=group.section_judge_spec,
        )
        assert await group.get_cache_key(section_context) != await retargeted_group.get_cache_key(
            section_context
        )

        moving_heads = MovingHeadPlannerOrchestrator(provider=provider)
        retargeted_mh = MovingHeadPlannerOrchestrator(
            provider=provider,
            planner_spec=_retarget(moving_heads.planner_spec),
            judge_spec=moving_heads.judge_spec,
        )
        assert await moving_heads.get_cache_key(
            moving_heads_context
        ) != await retargeted_mh.get_cache_key(moving_heads_context)

    async def test_reasoning_effort_changes_every_llm_stage_key(
        self,
        provider: MagicMock,
        audio_packs: Path,
        macro_context: PlanningContext,
        section_context: SectionPlanningContext,
        moving_heads_context: MovingHeadPlanningContext,
        song_bundle: SongBundle,
    ) -> None:
        profile = AudioProfileOrchestrator(provider=provider, prompt_base_path=audio_packs)
        changed_profile = AudioProfileOrchestrator(
            provider=provider, reasoning_effort="high", prompt_base_path=audio_packs
        )
        assert await profile.get_cache_key(song_bundle) != await changed_profile.get_cache_key(
            song_bundle
        )

        lyrics = LyricsOrchestrator(provider=provider, prompt_base_path=audio_packs)
        changed_lyrics = LyricsOrchestrator(
            provider=provider, reasoning_effort="high", prompt_base_path=audio_packs
        )
        assert await lyrics.get_cache_key(song_bundle) != await changed_lyrics.get_cache_key(
            song_bundle
        )

        macro = MacroPlannerOrchestrator(provider=provider)
        changed_macro = MacroPlannerOrchestrator(
            provider=provider,
            planner_spec=_change_reasoning(macro.planner_spec),
            judge_spec=macro.judge_spec,
        )
        assert await macro.get_cache_key(macro_context) != await changed_macro.get_cache_key(
            macro_context
        )

        group = GroupPlannerOrchestrator(provider=provider)
        changed_group = GroupPlannerOrchestrator(
            provider=provider,
            planner_spec=_change_reasoning(group.planner_spec),
            section_judge_spec=group.section_judge_spec,
        )
        assert await group.get_cache_key(section_context) != await changed_group.get_cache_key(
            section_context
        )

        moving_heads = MovingHeadPlannerOrchestrator(provider=provider)
        changed_mh = MovingHeadPlannerOrchestrator(
            provider=provider,
            planner_spec=_change_reasoning(moving_heads.planner_spec),
            judge_spec=moving_heads.judge_spec,
        )
        assert await moving_heads.get_cache_key(
            moving_heads_context
        ) != await changed_mh.get_cache_key(moving_heads_context)


def _retarget(spec: AgentSpec) -> AgentSpec:
    """Same spec pointed at a different model."""
    return spec.model_copy(update={"model": "gpt-5.6"})


def _change_reasoning(spec: AgentSpec) -> AgentSpec:
    """Same spec with a different explicit reasoning effort."""
    effort = "low" if spec.reasoning_effort != "low" else "high"
    return spec.model_copy(update={"reasoning_effort": effort})


class TestPromptPackHashing:
    """Behavior of the hashing primitives themselves."""

    def test_hash_changes_with_content(self, audio_packs: Path) -> None:
        before = prompt_pack_hash(audio_packs, "audio_profile")
        _edit_prompt(audio_packs / "audio_profile")

        assert prompt_pack_hash(audio_packs, "audio_profile") != before

    def test_hash_is_stable_for_identical_content(self, audio_packs: Path) -> None:
        assert prompt_pack_hash(audio_packs, "audio_profile") == prompt_pack_hash(
            audio_packs, "audio_profile"
        )

    def test_missing_pack_is_marked_not_raised(self, tmp_path: Path) -> None:
        assert prompt_pack_hash(tmp_path, "no_such_pack") == MISSING_PACK_MARKER

    def test_adding_a_file_changes_the_hash(self, audio_packs: Path) -> None:
        before = prompt_pack_hash(audio_packs, "audio_profile")
        (audio_packs / "audio_profile" / "user_refinement.j2").write_text("refine this")

        assert prompt_pack_hash(audio_packs, "audio_profile") != before

    def test_combined_hash_is_order_independent(self, audio_packs: Path) -> None:
        forward = prompt_packs_hash([(audio_packs, "audio_profile"), (audio_packs, "lyrics")])
        reverse = prompt_packs_hash([(audio_packs, "lyrics"), (audio_packs, "audio_profile")])

        assert forward == reverse

    def test_spec_hash_covers_every_referenced_pack(self, audio_packs: Path) -> None:
        profile_spec = AgentSpec(name="p", prompt_pack="audio_profile", response_model=dict)
        lyrics_spec = AgentSpec(name="l", prompt_pack="lyrics", response_model=dict)

        before = spec_prompt_hash(audio_packs, profile_spec, lyrics_spec)
        _edit_prompt(audio_packs / "lyrics")

        assert spec_prompt_hash(audio_packs, profile_spec, lyrics_spec) != before
