"""Typed, local-only integration with xLights' HTTP automation API."""

from twinklr.core.api.xlights.client import XLightsAutomationClient
from twinklr.core.api.xlights.errors import (
    XLightsAutomationError,
    XLightsClientClosedError,
    XLightsCommandError,
    XLightsInstanceUnavailableError,
    XLightsTimeoutError,
)
from twinklr.core.api.xlights.fseq import FseqComparison, compare_fseqs
from twinklr.core.api.xlights.injection import (
    TWINKLR_LAYER_BASE,
    InjectionCollisionError,
    InjectionPartialError,
    InjectionResult,
    JsonOwnershipStore,
    LayoutDivergenceReport,
    LiveEffect,
    LiveInjectionWorkflow,
    LiveLayoutReconciliation,
    MemoryOwnershipStore,
    live_effects_from_segments,
    reconcile_live_layout,
)
from twinklr.core.api.xlights.models import (
    AddEffectRequest,
    CheckSequenceRequest,
    CheckSequenceResult,
    CloseSequenceRequest,
    CommandResult,
    DeleteEffectRequest,
    EffectIdsResult,
    EffectSettingsResult,
    ExportVideoPreviewRequest,
    ExportVideoPreviewResult,
    GetEffectIdsRequest,
    GetEffectSettingsRequest,
    GetModelsRequest,
    GetModelsResult,
    GetOpenSequenceRequest,
    GetViewsRequest,
    GetViewsResult,
    LoadSequenceRequest,
    LoadSequenceResult,
    OpenSequenceResult,
    PreviewResult,
    RenderAllRequest,
)

__all__ = [
    "TWINKLR_LAYER_BASE",
    "AddEffectRequest",
    "CheckSequenceRequest",
    "CheckSequenceResult",
    "CloseSequenceRequest",
    "CommandResult",
    "DeleteEffectRequest",
    "EffectIdsResult",
    "EffectSettingsResult",
    "ExportVideoPreviewRequest",
    "ExportVideoPreviewResult",
    "FseqComparison",
    "GetEffectIdsRequest",
    "GetEffectSettingsRequest",
    "GetModelsRequest",
    "GetModelsResult",
    "GetOpenSequenceRequest",
    "GetViewsRequest",
    "GetViewsResult",
    "InjectionCollisionError",
    "InjectionPartialError",
    "InjectionResult",
    "JsonOwnershipStore",
    "LayoutDivergenceReport",
    "LiveEffect",
    "LiveInjectionWorkflow",
    "LiveLayoutReconciliation",
    "LoadSequenceRequest",
    "LoadSequenceResult",
    "MemoryOwnershipStore",
    "OpenSequenceResult",
    "PreviewResult",
    "RenderAllRequest",
    "XLightsAutomationClient",
    "XLightsAutomationError",
    "XLightsClientClosedError",
    "XLightsCommandError",
    "XLightsInstanceUnavailableError",
    "XLightsTimeoutError",
    "compare_fseqs",
    "live_effects_from_segments",
    "reconcile_live_layout",
]
