"""Feature engineering contract constants."""

from __future__ import annotations

FEATURE_BUNDLE_SCHEMA_VERSION = "v1.0.0"
ALIGNED_EVENTS_SCHEMA_VERSION = "v1.1.0"
EFFECT_PHRASES_SCHEMA_VERSION = "v1.2.0"
PHRASE_TAXONOMY_SCHEMA_VERSION = "v1.3.0"
TARGET_ROLES_SCHEMA_VERSION = "v1.4.0"
TEMPLATE_CATALOG_SCHEMA_VERSION = "v1.5.0"
TRANSITION_GRAPH_SCHEMA_VERSION = "v1.6.0"
LAYERING_FEATURES_SCHEMA_VERSION = "v1.7.0"
COLOR_NARRATIVE_SCHEMA_VERSION = "v1.8.0"
QUALITY_REPORT_SCHEMA_VERSION = "v1.9.0"
MOTIF_CATALOG_SCHEMA_VERSION = "v2.0.0"
CLUSTER_CATALOG_SCHEMA_VERSION = "v2.1.0"
LEARNED_TAXONOMY_SCHEMA_VERSION = "v2.2.0"
ANN_RETRIEVAL_SCHEMA_VERSION = "v2.3.0"
