"""Phoneme and viseme models (Phase 6).

Models for phoneme-level analysis and viseme mouth shapes:
- Phoneme: Single phoneme with timing
- VisemeEvent: Viseme mouth shape event
- PhonemeBundle: Complete phoneme/viseme analysis result
- PhonemeSource: Source of phoneme data

Example:
    >>> phonemes = [
    ...     Phoneme(text="HH", start_ms=0, end_ms=50),
    ...     Phoneme(text="EH1", start_ms=50, end_ms=150),
    ... ]
    >>> bundle = PhonemeBundle(
    ...     phonemes=phonemes,
    ...     source=PhonemeSource.G2P
    ... )
"""

from enum import Enum

from pydantic import BaseModel, ConfigDict, Field


class PhonemeSource(str, Enum):
    """Source of phoneme data.

    Values:
        G2P: Generated by G2P (grapheme-to-phoneme) library
        CMUDICT: Looked up from CMUdict
        ALLOSAURUS: Generated by Allosaurus phoneme recognizer
    """

    G2P = "g2p"
    CMUDICT = "cmudict"
    ALLOSAURUS = "allosaurus"


class Phoneme(BaseModel):
    """Single phoneme with timing.

    Represents a phoneme (speech sound) with start/end timing.

    Attributes:
        text: Phoneme text (ARPAbet format, e.g., "AH0", "IY1")
        start_ms: Phoneme start time in milliseconds
        end_ms: Phoneme end time in milliseconds
        phoneme_type: Optional phoneme type (VOWEL, CONSONANT, SILENCE)

    Example:
        >>> phoneme = Phoneme(text="AH0", start_ms=0, end_ms=100)
        >>> phoneme.text
        'AH0'
    """

    model_config = ConfigDict(extra="forbid")

    text: str = Field(description="Phoneme text (ARPAbet)")
    start_ms: int = Field(ge=0, description="Phoneme start time (milliseconds)")
    end_ms: int = Field(ge=0, description="Phoneme end time (milliseconds)")
    phoneme_type: str | None = Field(
        default=None, description="Phoneme type (VOWEL, CONSONANT, SILENCE)"
    )


class VisemeEvent(BaseModel):
    """Viseme mouth shape event.

    Represents a viseme (visual phoneme) for lip-sync animation.

    Attributes:
        viseme: Viseme code (A, E, I, O, U, BMP, FV, TH, L, REST, etc.)
        start_ms: Event start time in milliseconds
        end_ms: Event end time in milliseconds
        confidence: Viseme confidence (0-1)

    Standard Viseme Codes:
        A - open mouth (ah, aa)
        E - slightly open (eh, ae)
        I - smile (ee, ih)
        O - rounded (oh, oo)
        U - pucker (oo, uw)
        BMP - lips together (b, m, p)
        FV - bottom lip to teeth (f, v)
        TH - tongue between teeth
        L - tongue to roof
        REST - neutral/silence

    Example:
        >>> event = VisemeEvent(
        ...     viseme="A",
        ...     start_ms=0,
        ...     end_ms=150,
        ...     confidence=0.9
        ... )
        >>> event.viseme
        'A'
    """

    model_config = ConfigDict(extra="forbid")

    viseme: str = Field(description="Viseme code")
    start_ms: int = Field(ge=0, description="Event start time (milliseconds)")
    end_ms: int = Field(ge=0, description="Event end time (milliseconds)")
    confidence: float = Field(default=1.0, ge=0.0, le=1.0, description="Viseme confidence")


class PhonemeBundle(BaseModel):
    """Complete phoneme/viseme analysis result.

    Contains phonemes, visemes, and metadata from phoneme analysis.

    Attributes:
        phonemes: List of phonemes with timing
        visemes: List of viseme events (optional)
        source: Source of phoneme data
        metadata: Additional metadata

    Example:
        >>> phonemes = [Phoneme(text="HH", start_ms=0, end_ms=50)]
        >>> visemes = [VisemeEvent(viseme="H", start_ms=0, end_ms=50, confidence=0.9)]
        >>> bundle = PhonemeBundle(
        ...     phonemes=phonemes,
        ...     visemes=visemes,
        ...     source=PhonemeSource.G2P,
        ...     metadata={"model": "g2p_en"}
        ... )
        >>> len(bundle.phonemes)
        1
    """

    model_config = ConfigDict(extra="forbid")

    phonemes: list[Phoneme]
    visemes: list[VisemeEvent] = Field(default_factory=list)
    source: PhonemeSource
    metadata: dict[str, object] = Field(default_factory=dict)
