"""Content hashing for prompt packs.

Cache keys for LLM stages carry the model ID but historically carried nothing
about the prompt, so editing a template served plans generated by the previous
one. These helpers hash the *content* of the pack directories a stage renders,
so a prompt edit invalidates exactly the stages that read that pack.

``pack.yaml``'s ``pack_version`` is deliberately not consulted: it is
hand-maintained and routinely stale, so the invalidation signal is computed from
the files themselves.
"""

from __future__ import annotations

import hashlib
from pathlib import Path

from twinklr.core.agents.spec import AgentSpec

MISSING_PACK_MARKER = "<missing>"
"""Recorded for packs that do not exist, so a key stays computable and still
changes if the pack is later added."""


def _hash_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def prompt_pack_hash(base_path: Path | str, pack_name: str) -> str:
    """Hash every file in one prompt pack directory.

    Args:
        base_path: Directory prompt packs resolve against
        pack_name: Pack directory name, relative to ``base_path``

    Returns:
        Hex digest over the pack's file names and contents, or
        :data:`MISSING_PACK_MARKER` if the pack directory does not exist
    """
    pack_dir = Path(base_path) / pack_name
    if not pack_dir.is_dir():
        return MISSING_PACK_MARKER

    digest = hashlib.sha256()
    for file_path in sorted(p for p in pack_dir.rglob("*") if p.is_file()):
        relative = file_path.relative_to(pack_dir).as_posix()
        digest.update(relative.encode("utf-8"))
        digest.update(b"\x00")
        digest.update(_hash_file(file_path).encode("utf-8"))
        digest.update(b"\x00")

    return digest.hexdigest()


def prompt_packs_hash(entries: list[tuple[Path | str, str]]) -> str:
    """Hash several prompt packs into one value.

    Args:
        entries: ``(base_path, pack_name)`` pairs, one per pack

    Returns:
        Hex digest covering all packs, order-independent
    """
    parts = sorted(
        f"{pack_name}:{prompt_pack_hash(base, pack_name)}" for base, pack_name in entries
    )
    return hashlib.sha256("|".join(parts).encode("utf-8")).hexdigest()


def spec_prompt_hash(base_path: Path | str, *specs: AgentSpec) -> str:
    """Hash the prompt packs used by the given agent specs.

    Args:
        base_path: Directory the specs' ``prompt_pack`` values resolve against
        *specs: Agent specs whose prompt packs the stage renders

    Returns:
        Hex digest covering every referenced pack's content
    """
    return prompt_packs_hash([(base_path, spec.prompt_pack) for spec in specs])
