"""Standard curve generators."""

from twinklr.core.curves.functions.basic import (
    generate_cosine,
    generate_hold,
    generate_linear,
    generate_pulse,
    generate_s_curve,
    generate_sine,
    generate_smooth_step,
    generate_smoother_step,
    generate_square,
    generate_triangle,
)
from twinklr.core.curves.functions.easing import (
    generate_bounce_in,
    generate_bounce_out,
    generate_ease_in_back,
    generate_ease_in_cubic,
    generate_ease_in_out_back,
    generate_ease_in_out_cubic,
    generate_ease_in_out_quad,
    generate_ease_in_out_sine,
    generate_ease_in_quad,
    generate_ease_in_sine,
    generate_ease_out_back,
    generate_ease_out_cubic,
    generate_ease_out_quad,
    generate_ease_out_sine,
    generate_elastic_in,
    generate_elastic_in_out,
    generate_elastic_out,
)
from twinklr.core.curves.functions.motion import generate_anticipate, generate_overshoot
from twinklr.core.curves.functions.movement import (
    generate_movement_hold,
    generate_movement_linear,
    generate_movement_pulse,
    generate_movement_sine,
    generate_movement_triangle,
)
from twinklr.core.curves.functions.musical import (
    generate_beat_pulse,
    generate_musical_accent,
    generate_musical_swell,
)
from twinklr.core.curves.functions.noise import (
    generate_perlin_noise,
)
from twinklr.core.curves.functions.parametric import generate_bezier, generate_lissajous

__all__ = [
    "generate_linear",
    "generate_hold",
    "generate_sine",
    "generate_triangle",
    "generate_pulse",
    "generate_cosine",
    "generate_s_curve",
    "generate_smooth_step",
    "generate_smoother_step",
    "generate_square",
    "generate_ease_in_sine",
    "generate_ease_out_sine",
    "generate_ease_in_out_sine",
    "generate_ease_in_quad",
    "generate_ease_out_quad",
    "generate_ease_in_out_quad",
    "generate_ease_in_cubic",
    "generate_ease_out_cubic",
    "generate_ease_in_out_cubic",
    "generate_ease_in_back",
    "generate_ease_out_back",
    "generate_ease_in_out_back",
    "generate_bounce_out",
    "generate_bounce_in",
    "generate_elastic_out",
    "generate_elastic_in",
    "generate_elastic_in_out",
    "generate_perlin_noise",
    "generate_bezier",
    "generate_lissajous",
    "generate_anticipate",
    "generate_overshoot",
    "generate_movement_linear",
    "generate_movement_hold",
    "generate_movement_sine",
    "generate_movement_triangle",
    "generate_movement_pulse",
    "generate_musical_accent",
    "generate_musical_swell",
    "generate_beat_pulse",
]
